# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: zebra_printer 0.1.0 ruby lib

Gem::Specification.new do |s|
  s.name = "zebra_printer"
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Paul Mitchell"]
  s.date = "2014-04-01"
  s.description = "This DSL is for zebra printers and support languages ZPLII and EPLII"
  s.email = "paul.d.mitchell@ed.ac.uk"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    ".rspec",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "features/ascii-text-rotation.feature",
    "features/ascii-text-simple.feature",
    "features/ascii-text-size.feature",
    "features/barcode-code128.feature",
    "features/barcode-datamatrix.feature",
    "features/step_definitions/dsl_steps.rb",
    "features/step_definitions/language_steps.rb",
    "features/step_definitions/output_steps.rb",
    "features/support/env.rb",
    "lib/document_value.rb",
    "lib/languages.rb",
    "lib/languages/epl2.rb",
    "lib/languages/epl2/barcode.rb",
    "lib/languages/epl2/document.rb",
    "lib/languages/epl2/font.rb",
    "lib/languages/epl2/position.rb",
    "lib/languages/epl2/text.rb",
    "lib/languages/zpl2.rb",
    "lib/languages/zpl2/barcode.rb",
    "lib/languages/zpl2/document.rb",
    "lib/languages/zpl2/font.rb",
    "lib/languages/zpl2/position.rb",
    "lib/languages/zpl2/text.rb",
    "lib/utils/array.rb",
    "lib/zebra_printer.rb",
    "lib/zebra_printer_document.rb",
    "spec/eplii/ascii_text_spec.rb",
    "spec/spec_helper.rb",
    "spec/zebra_printer_spec.rb"
  ]
  s.homepage = "http://github.com/yatsura/zebra_printer"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "2.1.11"
  s.summary = "Zebra printer DSL"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, ["~> 2.14.0"])
      s.add_development_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 2.0.1"])
      s.add_development_dependency(%q<simplecov>, [">= 0"])
      s.add_development_dependency(%q<cucumber>, [">= 0"])
    else
      s.add_dependency(%q<rspec>, ["~> 2.14.0"])
      s.add_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_dependency(%q<bundler>, ["~> 1.0"])
      s.add_dependency(%q<jeweler>, ["~> 2.0.1"])
      s.add_dependency(%q<simplecov>, [">= 0"])
      s.add_dependency(%q<cucumber>, [">= 0"])
    end
  else
    s.add_dependency(%q<rspec>, ["~> 2.14.0"])
    s.add_dependency(%q<rdoc>, ["~> 3.12"])
    s.add_dependency(%q<bundler>, ["~> 1.0"])
    s.add_dependency(%q<jeweler>, ["~> 2.0.1"])
    s.add_dependency(%q<simplecov>, [">= 0"])
    s.add_dependency(%q<cucumber>, [">= 0"])
  end
end

